#!/bin/bash

if [[ !( -f setvars.sh ) ]]; then
	echo setvars.sh not found, create it
fi

find -name \*~ -delete
find -name \*.log -delete
find -name \*.lo1 -delete
. setvars.sh
rm -v bld/build/binl/wtouch
./clean
rm -Rfv rel2 bld/build/binl/wtouch bld/w32api.old/nt386/{base,ddk,directx}
(cd bld && find -name \*.obj -delete)
(cd bld && find -name \*.lib -delete)
(cd bld/browser && find -name \*.exe -delete)
(cd bld/browser && find -name \*.map -delete)
(cd bld/browser && find -name \*.sym -delete)
(cd bld/browser && find -name \*.gh -delete)
(cd bld/browser && find -name \*.gpp -delete)
(cd bld/browser && find -name \*.err -delete)
(cd bld/ndisasm && find -name \*.exe -delete)
(cd bld/mstools && find -name \*.exe -delete)
(cd bld/rtdll && find -name \*.exe -delete)
(cd bld/wprof && find -name \*.exe -delete)
(cd bld/bdiff && find -name \*.exe -delete)
(cd bld/bdiff && find -name \*.map -delete)
(cd bld/bdiff && find -name \*.sym -delete)
(cd bld/bdiff && find -name \*.res -delete)
(cd bld/mad && find -name \*.exe -delete)
#(cd bld/viper && find -name \*.exe -delete)
#(cd bld/viprdemo && find -name \*.exe -delete)
#(cd bld/viper && find -name \*.map -delete)
#(cd bld/viprdemo && find -name \*.map -delete)
#(cd bld/viper && find -name \*.sym -delete)
#(cd bld/viprdemo && find -name \*.sym -delete)
(cd bld/wstuba && find -name \*.exe -delete)
(cd bld/wstuba && find -name \*.sym -delete)
(cd contrib && find -name \*.obj -delete)

