#pmake/50: build os_win32s cpu_386

host_os       = win32s
host_cpu      = 386
system        = win32s

root_dir      = ..
include_dir   = $(root_dir)/include
lib_dir       = $(root_dir)/lib
what_to_build = libs

!include ../master.mif
