/*
 *  initguid.h  Enable initialization of GUIDs
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2010 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file;
#endif

/* Redefine the macro DEFINE_GUID to initialize the GUID. */
#undef DEFINE_GUID
#define DEFINE_GUID( x, p1, p2, p3, p5, p6, p7, p8, p9, p10, p11 ) \
    EXTERN_C const GUID CDECL x = \
        { p1, p2, p3, { p4, p5, p6, p7, p8, p9, p10, p11 } }
